# Use overmind (https://github.com/DarthSim/overmind)

# \x02gkvmesh-dev-cluster-1\x00
node-1: ./start_one.sh -Dgkvmesh.meshserver.port=6201 -Dgkvmesh.httpapi.port=6301 -Dgkvmesh.log.localLevel=info -Dgkvmesh.tkv.prefixHex=02676b766d6573682d6465762d636c75737465722d3100

# \x02gkvmesh-dev-cluster-2\x00
node-2: ./start_one.sh -Dgkvmesh.meshserver.port=6202 -Dgkvmesh.httpapi.port=6302 -Dgkvmesh.log.localLevel=info -Dgkvmesh.tkv.prefixHex=02676b766d6573682d6465762d636c75737465722d3200

# \x02gkvmesh-dev-cluster-3\x00
node-3: ./start_one.sh -Dgkvmesh.meshserver.port=6203 -Dgkvmesh.httpapi.port=6303 -Dgkvmesh.log.localLevel=info -Dgkvmesh.tkv.prefixHex=02676b766d6573682d6465762d636c75737465722d3300
